### PR TITLE
Optimize user interface

### PR DESCRIPTION
**Pull request by gearsdigital**
I optimized the UI a little bit by reducing some spacings which should render the dialog a bit more tidy. All "advanced"  settings are now hidden initally. The are getting rendered once a user want do show them.

Bildschirmfoto 2021-11-29 um 19 58 57

Bildschirmfoto 2021-11-29 um 19 58 48

### CODE REVIEW

**Comment by gearsdigital** [comment]
@herrajon What do you say?

**Comment by herrajon** [comment]
@gearsdigital That is beautiful that is

**Pull request merged**
