### PR TITLE
Added title and anchor bookmarks fields to internal links

### PR DESCRIPTION
**Pull request by mvilskersts**
This PR adds a title and anchor bookmark field to internal links tab as well as `rel="nofollow"` to external links. This is something that we need in our current project and would be great if we could use the original repo instead of forked one. 

Let me know if there are any issues or concerns.

### CODE REVIEW

**Comment by gearsdigital** [comment]
@mvilskersts Thank you very much for contributing! I'll have a look on that later today…

**Comment by gearsdigital** [comment]
@mvilskersts I reviewed your changes and it works as described. Great job 👍 

As I don't have rights tu push to your PR would you mind to fix and extend the tests?

You can verify this by running `$(npm bin)/cypress run` from the plugin directory.

Just to updates these two files:

1. cypress/support/commands.js
```js
// ***********************************************
// This example commands.js shows you how to
// create various custom commands and overwrite
// existing commands.
//
// For more comprehensive examples of custom
// commands please read more here:
// https://on.cypress.io/custom-commands
// ***********************************************
//
//
// -- This is a parent command --
Cypress.Commands.add('login', function (options = {}) {
  cy.visit('http://localhost:8000/panel');
  cy.fixture('user').then((user) => {
    cy.get('.k-panel-view').within(function () {

      cy.get('input[type="email"]')
        .clear()
        .type(user.email)

      cy.get('input[type="password"]')
        .clear()
        .type(user.password)

      cy.get('button')
        .click({force: true})
    })
    cy.url().should('include', '/panel')
  })
});

Cypress.Commands.add('openFirstNote', function (options = {}) {
  cy.visit('http://localhost:8000/panel');

  cy.get('.k-section-name-notes li:first-child a')
    .click({force: true})
});

Cypress.Commands.add('openDialog', function (options = {}) {
  cy.get('.k-toolbar .k-icon-url').click({force: true})
});

Cypress.Commands.add('openInternalTab', function (options = {}) {
  cy.get(".k-dialog-body nav").contains("Internal Link").click({force: true});
});
```

2. cypress/integration/dialog_spec.js
```js
describe("Enhanced Link Toolbar Dialog", () => {
  it("should filter pages correctly while searching", () => {
    cy.login();
    cy.openFirstNote();
    cy.openDialog();
    cy.openInternalTab();

    cy.get(".k-dialog-search .k-text-input").type("jun",{delay: 500}).should("have.value", "jun");

    cy.wait(1000);

    cy.get(".k-pages-dialog .k-list")
      .find(".k-list-item")
      .should("have.length", 1);
  });

  it("should paginate correctly", () => {
    cy.login();
    cy.openFirstNote();
    cy.openDialog();
    cy.openInternalTab();

    cy.get(".k-pages-dialog .k-dialog-pagination")
      .find('button[title="Next"]')
      .click({force: true})
      .click({force: true});

    cy.get(".k-pages-dialog .k-list")
      .find(".k-list-item")
      .should("have.length", 1);
  });

  describe("Options", () => {
    beforeEach(() => {
      cy.task('copyKirbyConfig');
      cy.login();
      cy.openFirstNote();
      cy.openDialog();
    });

    afterEach(() => {
      cy.task('restoreKirbyConfig')
    });

    it('link.title and tab.order', () => {
      cy.wait(2000);

      cy.get(".k-pages-dialog .k-list-item:first-child")
        .should(
          "include.text",
          "###"
        );
    });
  });

  describe("KirbyText", () => {
    describe("with selected link", () => {

      it('should insert "text:" from page name', () => {
        cy.login();
        cy.openFirstNote();

        cy.get(".k-textarea-field textarea").clear();

        cy.openDialog();
        cy.openInternalTab();

        cy.get(".k-pages-dialog .k-list")
          .find(".k-list-item:first-child")
          .click({force: true});

        cy.get(".k-button").contains("Ok").click({force: true});

        cy.get(".k-textarea-field textarea").should(
          "include.value",
          "(link: /notes/in-the-jungle-of-sumatra text: ### In the jungle of Sumatra ###)"
        );
      });

      it('should insert "text:" from selection', () => {
        cy.login();
        cy.openFirstNote();

        cy.get(".k-textarea-field textarea")
          .clear()
          .type("Lorem ipsum dolor")
          .type("{selectall}");

        cy.openDialog();
        cy.openInternalTab();

        cy.get(".k-pages-dialog .k-list")
          .find(".k-list-item:first-child")
          .click({force: true});

        cy.get(".k-button").contains("Ok").click({force: true});

        cy.get(".k-textarea-field textarea").should(
          "include.value",
          "(link: /notes/in-the-jungle-of-sumatra text: Lorem ipsum dolor)"
        );
      });

      it('should insert "text:" from selection and "target:" from dropdown', () => {
        cy.login();
        cy.openFirstNote();

        cy.get(".k-textarea-field textarea")
          .clear()
          .type("Lorem ipsum dolor")
          .type("{selectall}");

        cy.openDialog();
        cy.openInternalTab();

        cy.get(".k-pages-dialog .k-list")
          .find(".k-list-item:first-child")
          .click({force: true});
        cy.get(".k-pages-dialog .k-select-input-native").select("Blank");

        cy.get(".k-button").contains("Ok").click({force: true});

        cy.get(".k-textarea-field textarea").should(
          "include.value",
          "(link: /notes/in-the-jungle-of-sumatra text: Lorem ipsum dolor target: _blank)"
        );
      });

      it('should insert "text:" from selection with #anchor', () => {
        cy.login();
        cy.openFirstNote();

        cy.get(".k-textarea-field textarea")
          .clear()
          .type("Lorem ipsum dolor")
          .type("{selectall}");

        cy.openDialog();
        cy.openInternalTab();

        cy.get(".k-pages-dialog .k-list")
          .find(".k-list-item:first-child")
          .click({force: true});

        cy.get(".k-pages-dialog .k-select-input-native").select("Blank");
        cy.get(".k-pages-dialog .k-field-name-anchor .k-text-input").type("anchor")

        cy.get(".k-button").contains("Ok").click({force: true});
        cy.get(".k-textarea-field textarea").should(
          "include.value",
          "(link: /notes/in-the-jungle-of-sumatra#anchor text: Lorem ipsum dolor target: _blank)"
        );
      });

      it('should insert "text:" from selection with :title', () => {
        cy.login();
        cy.openFirstNote();

        cy.get(".k-textarea-field textarea")
          .clear()
          .type("Lorem ipsum dolor")
          .type("{selectall}");

        cy.openDialog();
        cy.openInternalTab();

        cy.get(".k-pages-dialog .k-list")
          .find(".k-list-item:first-child")
          .click({force: true});

        cy.get(".k-pages-dialog .k-select-input-native").select("Blank");
        cy.get(".k-pages-dialog .k-field-name-title .k-text-input").type("Title")

        cy.get(".k-button").contains("Ok").click({force: true});
        cy.get(".k-textarea-field textarea").should(
          "include.value",
          "(link: /notes/in-the-jungle-of-sumatra text: Lorem ipsum dolor target: _blank title: Title)"
        );
      });

      it('should insert "text:" from selection with anchor, :target and :title', () => {
        cy.login();
        cy.openFirstNote();

        cy.get(".k-textarea-field textarea")
          .clear()
          .type("Lorem ipsum dolor")
          .type("{selectall}");

        cy.openDialog();
        cy.openInternalTab();

        cy.get(".k-pages-dialog .k-list")
          .find(".k-list-item:first-child")
          .click({force: true});

        cy.get(".k-pages-dialog .k-select-input-native").select("Blank");
        cy.get(".k-pages-dialog .k-field-name-anchor .k-text-input").type("anchor");
        cy.get(".k-pages-dialog .k-field-name-title .k-text-input").type("Title");

        cy.get(".k-button").contains("Ok").click({force: true});
        cy.get(".k-textarea-field textarea").should(
          "include.value",
          "(link: /notes/in-the-jungle-of-sumatra#anchor text: Lorem ipsum dolor target: _blank title: Title)"
        );
      });
    });

    describe("without selected link", () => {
      it("should insert nothing", () => {
        cy.login();
        cy.openFirstNote();

        cy.get(".k-textarea-field textarea").clear().type("Lorem ipsum dolor");

        cy.openDialog();
        cy.openInternalTab();

        cy.get(".k-button").contains("Ok").click({force: true});

        cy.get(".k-textarea-field textarea").should(
          "include.value",
          "Lorem ipsum dolor"
        );
      });

      it("should insert nothing even with selection", () => {
        cy.login();
        cy.openFirstNote();

        cy.get(".k-textarea-field textarea")
          .clear()
          .type("Lorem ipsum dolor")
          .type("{selectall}");

        cy.openDialog();
        cy.openInternalTab();

        cy.get(".k-button").contains("Ok").click({force: true});

        cy.get(".k-textarea-field textarea").should(
          "include.value",
          "Lorem ipsum dolor"
        );
      });
    });
  });
});
```

**Comment by mvilskersts** [comment]
@gearsdigital 
I've never worked with cypress so I am not entirely sure how it works. I did apply your changes. 
All of the tests fail when run locally because it never gets past the login.
Only 1 of the tests fail when run by Github Actions because of the added hashes to the expected text. Are those really supposed to be there?

**Comment by gearsdigital** [comment]
Yes the hashes are expected because I changed the config to do so.

This is the first time I use cypress too. The whole test setup is a bit flaky and needs some effort I guess.

Anyhow… I verified your changes manually and it works - so I'm gonna merge your changes and fix the tests afterwards. Thanks again for your effort. Very appreciated!

**Pull request merged**
